FROM centos:latest

RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-* &&\
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*

# install OS packages
RUN yum update -y \
    && yum groupinstall 'Development Tools' -y \
    && yum install -y \
#       autoconf \
#       autotools-dev \
#       automake \
#       bison \
       bzip2 \
#       curl \
       cmake \
       cyrus-sasl-devel \
       cyrus-sasl-plain \
       gdb \
       git-core \
       less \
       libcurl-devel \
       libpq-devel \
#       libcurl4-gnutls-dev \
#       libmysqlclient-dev \
#       libpq-dev \
#       libpcre3-dev \
#       libreadline-dev \
#       libsasl2-dev \
#       libssl-dev \
#       openjdk-8-jdk \
       nodejs \
       openssl-devel \
       pcre \
       pcre-devel \
       psmisc \
       readline-devel \
       tcl \
       tmux \
       tree \
       vim \
       zlib-devel \
    && rm -rf /var/lib/apt/lists/*

# update node to current stable version
RUN npm cache clean -f && npm install -g n && n stable

# rbenv setup
# use rbenv-default-gems to automatically install bundler for each ruby version
RUN  git clone https://github.com/rbenv/rbenv.git ~/.rbenv \
     && git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build \
     && git clone https://github.com/rbenv/rbenv-default-gems.git ~/.rbenv/plugins/rbenv-default-gems \
     && echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.profile \
     && echo 'eval "$(rbenv init -)"' >> ~/.profile \
     && echo 'eval "$(rbenv init -)"' >> ~/.bashrc \
     && echo 'bundler' > ~/.rbenv/default-gems

RUN echo 'alias be="bundle exec"' >> ~/.bashrc
RUN echo 'alias be="bundle exec"' >> ~/.profile

# install rubies to build our gem against
RUN . ~/.profile \
    && cd /root/.rbenv/plugins/ruby-build && git pull && cd - \
    && rbenv install 2.4.10 \
    && rbenv install 2.5.9 \
    && rbenv install 2.6.9 \
    && rbenv install 2.7.5 \
    && rbenv install 3.0.3

 # need to provide bundler 1.17.3 as well, because some gems require bundler < 2.0
#RUN . ~/.profile && rbenv local 2.4.10 && gem install bundler -v 1.17.3
#RUN . ~/.profile && rbenv local 2.5.8 && gem install bundler -v 1.17.3
#RUN . ~/.profile && rbenv local 2.6.8 && gem install bundler -v 1.17.3
#RUN . ~/.profile && rbenv local 2.7.4 && gem install bundler -v 1.17.3
#RUN . ~/.profile && rbenv local 3.0.2 && gem install bundler -v 1.17.3
RUN echo 'gem: --no-document' >> ~/.gemrc

# install swig 4.0.2
RUN curl -SL https://github.com/swig/swig/archive/refs/tags/v4.0.2.tar.gz \
    | tar xzC /tmp \
    && cd /tmp/swig-4.0.2 \
    && ./autogen.sh && ./configure && make && make install \
    && cd - \
    && rm -rf /tmp/swig-4.0.2

# install redis-server version 4++
RUN curl -SL http://download.redis.io/releases/redis-6.2.4.tar.gz | tar xzC /tmp \
    && cd /tmp/redis-6.2.4/ \
    && make  && make install && cd -

# install postgres and memcached
#RUN yum update -y \
#    && yum install -y \
#       memcached
#       postgresql \
#       postgresql-server \
#       postgresql-contrib \
#    && postgresql-setup --initdb --unit postgresql \
#    && systemctl start postgresql \
#    && systemctl enable postgresql \
#    && echo "psql --command \"CREATE USER docker WITH SUPERUSER PASSWORD 'docker';\"" >> /tmp/config \
#    && echo "createdb -O docker travis_ci_test" >> /tmp/config \
#    && su postgres -c "bash /tmp/config" \
#    && rm -f /tmp/config

RUN yum update -y && \
	yum -y install initscripts memcached mysql mysql-devel

RUN echo "echo never > /sys/kernel/mm/transparent_hugepage/enabled" >> /etc/rc.local

ENV PATH="/root/.rbenv/bin:/root/.rbenv/shims:$PATH"

CMD /bin/bash
