# Dockerfile
# Copyright (c) 2019 SolarWinds, LLC.
# All rights reserved.

FROM ubuntu:20.04

ENV TZ=America/Vancouver
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# install OS packages
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       apt-utils \
       autoconf \
       autotools-dev \
       automake \
       bash \
       bison \
       build-essential \
       cmake \
       curl \
       gdb \
       git-core \
       less \
       libcurl4-gnutls-dev \
       default-libmysqlclient-dev \
       libpq-dev \
       libpcre3-dev \
       libreadline-dev \
       libsasl2-dev \
       libsqlite3-dev \
       libssl-dev \
       nodejs \
       openjdk-8-jdk \
       pkg-config \
       psmisc \
       ruby \
       tcl \
       tmux \
       tree \
       vim \
       zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

# install yarn
#RUN curl -o- -L https://yarnpkg.com/install.sh | bash

# rbenv setup
# use rbenv-default-gems to automatically install bundler for each ruby version
RUN  git clone https://github.com/rbenv/rbenv.git ~/.rbenv \
     && git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build \
     && git clone https://github.com/rbenv/rbenv-default-gems.git ~/.rbenv/plugins/rbenv-default-gems \
     && echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.profile \
     && echo 'eval "$(rbenv init -)"' >> ~/.profile \
     && echo 'eval "$(rbenv init -)"' >> ~/.bashrc \
     && echo 'bundler' > ~/.rbenv/default-gems

RUN echo 'alias be="bundle exec"' >> ~/.bashrc
RUN echo 'alias be="bundle exec"' >> ~/.profile

# install rubies to build our gem against
RUN . ~/.profile \
    && cd /root/.rbenv/plugins/ruby-build && git pull && cd - \
    && rbenv install 2.5.9 \
    && rbenv install 2.6.9 \
    && rbenv install 2.7.5 \
    && rbenv install 3.0.3 \
    && rbenv install 3.1.0

RUN echo 'gem: --no-document' >> ~/.gemrc

# install swig 4.0.2
RUN curl -SL https://github.com/swig/swig/archive/refs/tags/v4.0.2.tar.gz \
    | tar xzC /tmp \
    && cd /tmp/swig-4.0.2 \
    && ./autogen.sh \
    && ./configure && make && make install \
    && cd - \
    && rm -rf /tmp/swig-4.0.2

# install redis-server
RUN curl -SL https://download.redis.io/releases/redis-6.2.4.tar.gz | tar xzC /tmp \
    && cd /tmp/redis-6.2.4/ \
    && make  && make install && cd -

# install postgres and memcached
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
       memcached
#       postgresql \
#       postgresql-contrib \
#    && service postgresql start \
#    && echo "psql --command \"CREATE USER docker WITH SUPERUSER PASSWORD 'docker';\"" >> /tmp/config \
#    && echo "createdb -O docker test_db" >> /tmp/config \
#    && su postgres -c "bash /tmp/config" \
#    && rm -f /tmp/config

RUN apt-get update && \
	apt-get -y install mysql-client


# update node to current stable version
# apt install npm doesn't work in the initial apt install run
#RUN apt install -y --no-install-recommends npm && rm -rf /var/lib/apt/lists/*
#RUN npm cache clean -f && npm install -g n && n stable

ENV PATH="/usr/local/bin:/root/.rbenv/bin:/root/.rbenv/shims:$PATH"

CMD /bin/bash
