version: 2

updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  groups:
    misc:
      update-types:
        - minor
        - patch

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
