FROM ubuntu:16.04

# to use with ./run_tests_docker.rb
# docker build -f Dockerfile_test -t ruby_appoptics_apm .

# install OS packages
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       build-essential \
       apt-utils \
       curl \
       git-core \
       libpcre3-dev \
       libreadline-dev \
       libsasl2-dev \
       libssl-dev \
       openjdk-8-jdk \
       zlib1g-dev \
       libcurl4-gnutls-dev \
       libmysqlclient-dev \
       libpq-dev \
       vim \
       less \
       tree \
       psmisc \
    && rm -rf /var/lib/apt/lists/*

# rbenv setup
# use rbenv-default-gems to automatically install bundler for each ruby version
RUN  git clone https://github.com/rbenv/rbenv.git ~/.rbenv \
     && git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build \
     && git clone https://github.com/rbenv/rbenv-default-gems.git ~/.rbenv/plugins/rbenv-default-gems \
     && echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.profile \
     && echo 'eval "$(rbenv init -)"' >> ~/.profile \
     && echo 'bundler' > ~/.rbenv/default-gems

# install rubies to build our gem against
RUN . ~/.profile \
    && rbenv install 2.3.6 \
    && rbenv install 2.4.3 \
    && rbenv install 2.5.1
#    && rbenv install jruby-9.1.16.0

# install swig 3.0.8
RUN curl -SL http://kent.dl.sourceforge.net/project/swig/swig/swig-3.0.8/swig-3.0.8.tar.gz \
    | tar xzC /tmp \
    && cd /tmp/swig-3.0.8 \
    && ./configure && make && make install \
    && cd \
    && rm -rf /tmp/swig-3.0.8

# install postgres, redis, and memcached
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
       redis-server \
       memcached \
       postgresql \
       postgresql-contrib \
    && service postgresql start \
    && echo "psql --command \"CREATE USER docker WITH SUPERUSER PASSWORD 'docker';\"" >> /tmp/config \
    && echo "createdb -O docker travis_ci_test" >> /tmp/config \
    && su postgres -c "bash /tmp/config" \
    && rm -f /tmp/config

RUN apt-get update && \
	apt-get -y install mysql-client libmysqlclient-dev

ENV PATH="/root/.rbenv/bin:/root/.rbenv/shims:$PATH"
ENV RUBY_ENV=test
ENV DOCKER_PSQL_PASS=docker
ENV APPOPTICS_TOKEN_BUCKET_CAPACITY=1000
ENV APPOPTICS_TOKEN_BUCKET_RATE=1000
