# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: test/servers/grpc/grpc.proto for package 'grpctest'

require 'grpc'
require 'test/servers/grpc/grpc_pb'

module Grpctest
  module AddressService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'grpctest.AddressService'

      # unary
      rpc :store_address, Address, AddressId
      rpc :get_address, AddressId, Address
      rpc :cancel, NullMessage, NullMessage
      rpc :unimplemented, NullMessage, NullMessage
      # client streaming
      rpc :add_phones, stream(Phone), NullMessage
      rpc :client_stream_cancel, stream(Phone), NullMessage
      rpc :client_stream_unimplemented, stream(Phone), NullMessage
      # server streaming
      rpc :get_phones, AddressId, stream(Phone)
      rpc :server_stream_cancel, NullMessage, stream(Phone)
      rpc :server_stream_unimplemented, NullMessage, stream(Phone)
    end

    Stub = Service.rpc_stub_class
  end
end
