# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test/servers/grpc/grpc.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "grpctest.NullMessage" do
  end
  add_message "grpctest.Phone" do
    optional :number, :string, 1
    optional :type, :string, 2
  end
  add_message "grpctest.AddressId" do
    optional :id, :int32, 1
  end
  add_message "grpctest.Address" do
    optional :id, :message, 5, "grpctest.AddressId"
    optional :street, :string, 1
    optional :number, :int32, 2
    optional :town, :string, 3
    repeated :phonenumbers, :message, 4, "grpctest.Phone"
  end
end

module Grpctest
  NullMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("grpctest.NullMessage").msgclass
  Phone = Google::Protobuf::DescriptorPool.generated_pool.lookup("grpctest.Phone").msgclass
  AddressId = Google::Protobuf::DescriptorPool.generated_pool.lookup("grpctest.AddressId").msgclass
  Address = Google::Protobuf::DescriptorPool.generated_pool.lookup("grpctest.Address").msgclass
end
